### ISSUE TITLE
Warn or don't remove package if the version being released isn't built

### ISSUE THREAD

**Issue by ids1024** [pop-os/repo-release#155]
The build was failing, but this should not happen given `kernelstub` was still in `sync`. Did https://github.com/pop-os/repo-release/pull/151 somehow break things?

The version previously available was still in `pool`, but not `dists`.

As of https://github.com/pop-os/repo-release/pull/154, this is no longer an issue, but this shouldn't be possible so we should find the root cause.

**Comment by ids1024** [comment]
I think the issue must be that the source package did build successfully, but repo-release doesn't know which binary packages were supposed to build, or whether they fail or haven't built yet.

**Comment by jacobgkau** [comment]
Sorry for the noise, but this happened again with cosmic-dock after https://github.com/pop-os/repo-release/pull/178.

**Comment by 13r0ck** [comment]
This happened again with cosmic-comp https://github.com/pop-os/repo-release/pull/189
